name: Minify main page

on:
  push:
    branches: ['master']

jobs:
  minify:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm i -g minify@14.0.0
      - run: ls
      - run: |
          for file in **/*.{js,html,css} 
          do
            minify $file > $file.tmp && mv -f $file.tmp $file
          done

      - run: |
          git config user.name Lantang Satriatama
          git config user.email lstama@user.noreply.github.com
          git commit -am 'Minify ${{ github.sha }}'
          git push --force -u origin master:gh-pages
